/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Design tokens (theme-aware via CSS variables, see index.css)
        "wv-bg": "var(--bg)",
        "wv-surface": "var(--surface)",
        "wv-surface-2": "var(--surface-2)",
        "wv-border": "var(--border)",
        "wv-border-strong": "var(--border-strong)",
        "wv-text": "var(--text)",
        "wv-text-2": "var(--text-2)",
        "wv-text-3": "var(--text-3)",
        "wv-accent": "var(--accent)",
        "wv-accent-weak": "var(--accent-weak)",
        "wv-gain": "var(--gain)",
        "wv-gain-weak": "var(--gain-weak)",
        "wv-loss": "var(--loss)",
        "wv-loss-weak": "var(--loss-weak)",
        "wv-warn": "var(--warn)",
        "wv-warn-weak": "var(--warn-weak)",
        // Legacy palette, used by pages not yet refitted
        "surface": "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e5eeff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d3e4fe",
        "on-surface": "#0b1c30",
        "on-surface-variant": "#45474c",
        "inverse-surface": "#213145",
        "inverse-on-surface": "#eaf1ff",
        "outline": "#75777d",
        "outline-variant": "#c5c6cd",
        "surface-tint": "#545f73",
        "primary": "#091426",
        "on-primary": "#ffffff",
        "primary-container": "#1e293b",
        "on-primary-container": "#8590a6",
        "inverse-primary": "#bcc7de",
        "secondary": "#515f74",
        "on-secondary": "#ffffff",
        "secondary-container": "#d5e3fc",
        "on-secondary-container": "#57657a",
        "tertiary": "#00190e",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#00301f",
        "on-tertiary-container": "#24a375",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#d8e3fb",
        "primary-fixed-dim": "#bcc7de",
        "on-primary-fixed": "#111c2d",
        "on-primary-fixed-variant": "#3c475a",
        "secondary-fixed": "#d5e3fc",
        "secondary-fixed-dim": "#b9c7df",
        "on-secondary-fixed": "#0d1c2e",
        "on-secondary-fixed-variant": "#3a485b",
        "tertiary-fixed": "#85f8c4",
        "tertiary-fixed-dim": "#68dba9",
        "on-tertiary-fixed": "#002114",
        "on-tertiary-fixed-variant": "#005137",
        "background": "#f8f9ff",
        "on-background": "#0b1c30",
        "surface-variant": "#d3e4fe",
      },
      fontFamily: {
        // One family across the app (Geist); serif utilities are kept so older pages still compile
        serif: ['Geist', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        sans: ['Geist', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['"Geist Mono"', 'ui-monospace', 'monospace'],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.125rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "gutter-desktop": "1.5rem",
        "gutter-mobile": "1rem",
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "space-3xl": "4rem",
      },
    },
  },
  plugins: [],
}
